TILA-1969 reservation success processing
City-of-Helsinki/tilavarauspalvelu-ui pull request #554
Opened 2023-03-07 13:29 UTC by kieferbonk

2023-03-13 16:02 UTC, joonatank requested changes

2023-03-13 16:02 UTC, joonatank commented on ui/components/reservation/ReservationFail.tsx
> +            <StyledLink href="#" onClick={() => logout()}>
Link accessibility. /logout endpoint or as="button"

2023-03-15 13:09 UTC, kieferbonk commented on ui/pages/_app.tsx
> +  }, [removeShouldLogout, shouldLogout, showChild]);
The `showChild` value seems to be connected to the theme provider, which fails if initialised before mount. It's in use only in navigation and we'll have to decide if we want to really start using it or get rid of it at some point.

The logout procedure goes like this: a localstorage value is set that logout is in process, then logout is requested from authentication provider and if it fails to redirect user to local logout path (which it does 50% of the time), user is redirected to it if the localstorage value is set.

2023-03-15 15:25 UTC, joonatank approved these changes

2023-03-17 08:12 UTC, merged