TILA-2125 dynamic form validation
City-of-Helsinki/tilavarauspalvelu-ui pull request #647
Opened 2023-05-22 07:31 UTC by kieferbonk

2023-05-24 06:23 UTC, joonatank requested changes
Null checks.

2023-05-24 06:23 UTC, joonatank commented on ui/components/reservation/Step0.tsx
> +                      const top = element.getBoundingClientRect()?.y;
element: Element | null

2023-05-24 06:23 UTC, joonatank commented on ui/components/reservation/Step0.tsx
> +                        top: window.scrollY + top - 28,
top: number | null

2023-05-24 06:23 UTC, joonatank commented on ui/components/reservation/Step1.tsx
> +    top: window.scrollY + top - 28,
top: number | null

2023-05-24 06:23 UTC, joonatank commented on ui/components/reservation/Step1.tsx
> +  const checkbox = document.getElementById(`${id}-terms-accepted`);
getByElementId: (...) => Element | null

2023-05-26 06:14 UTC, kieferbonk commented on common/src/reservation-form/ReservationFormField.tsx
> +  ) => string;
Tried that, but became too hairy on admin side, which also uses the components.

2023-05-26 12:46 UTC, joonatank approved these changes

2023-06-02 07:53 UTC, merged