Adds short day of the week to the date, above my-units calendar
City-of-Helsinki/tilavarauspalvelu-ui pull request #958
Opened 2024-02-02 11:07 UTC by vincit-matu

2024-02-02 14:22 UTC, joonatank requested changes
Doesn't work, like we talked.  Just marking so it doesn't get merged accidentially.

2024-02-07 14:22 UTC, vincit-matu commented
> Doesn't work, like we talked. Just marking so it doesn't get merged accidentially.

Yup, the date input is broken all-in-all. Moved the weekday outside the `input`-element, but it would need design decisions and then styling according to those before being ready.

2024-02-08 12:38 UTC, joonatank commented on apps/ui/components/reservation-unit/Head.tsx
Got an extra commit here from the other PR :)

2024-02-08 13:56 UTC, vincit-matu commented on apps/ui/components/reservation-unit/Head.tsx
Hehe, fixed! 😊

2024-02-08 14:15 UTC, merged